[workspace]

[package]
name = "cudf-polars-quent"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "cudf_polars_quent"
crate-type = ["cdylib"]

[features]
default = ["collector"]
collector = []

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py311"] }
quent-collector-python = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6" }
quent-dynamic-attributes = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6" }
quent-instrumentation = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6", features = ["serde", "io-ndjson", "io-collector"] }
quent-io = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6", default-features = false, features = ["ndjson", "collector"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
quent-build-info = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6" }
quent-instrumentation-build = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6" }
quent-schema-codegen-python = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6" }
quent-yaml = { git = "https://github.com/rapidsai/quent", rev = "618aea08d4f9aa140133ccea97de598e0925f1e6" }
